dist: ubuntu
language: java
jdk:
- openjdk8
script:
- "./mvnw clean test -P test"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: ZqiH9rVN1v6ZaDOUtPvpLSQHYnXERcLkEtTmtw7TcYqjhAqSUosX0OMdAgE29oSmq0Bg5S/GuF+7y+as5m4+EqFk7tTzL2eCPCSFwgiYAizCru1t/FwwvnodtU7ICbuehdyAG5eSh0BhQoPL5Jt2hSLN84ziDRByDpBrnPGwHI9ieYaSm4OgoNucB06yRmzKKILfdZjFgOHvhuKJzWdujapkcoPaWcyIpi01LjWRQe8GNyWpy9SFsikrLFC+UDCmYR9JSV0mIGRlJz2uBNqKfqSqfiz3wz+0SJc9xQZJDX0a9OdLzK0WDArBpa+/4phV0fQ68uh/udFkm2O50vdTOnIHX/Q9FX/OANDVyfSoLSJSX5QaXGtrSZLBnw8EHdybAbZOVX+H+5lVK0KHyaB62hLhSQL3Y7hoPMJ3+xBnWVM0Ki4ahLuaBAqwpUG+98M6po3C94WOTcJQR+4lxco9ucjAiwiBvSmZpP6UCyqztomu0CkUNMC+npIwmfKadqRuWQcYI8hRUTLh6fw2GCoPCEHXurHv4QRh6SNjmaX3kua8ZnwIo80//gSdq/79xAx9iPCsYxxxqESpBLHs3LsQ6uLwWRCbigfQqfzI4G2lvl5mXS2Y3TeaIi9J/HgSte95LzvQ7BslSzylza0DC4gsjJGElcvgBObvHVstnelhBTQ=
  app:
    master: adm-c-test
  on:
    repo: viniciusecortez/alugo-camada-Adm
